#!/bin/sh


rm -rf build
cd fltk-src

cmake -B ../build -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DFLTK_BUILD_TEST=OFF -DFLTK_BUILD_EXAMPLES=OFF -DFLTK_BUILD_FLUID=OFF -DFLTK_BUILD_HTML_DOCS=OFF -DFLTK_BUILD_PDF_DOCS=OFF -DFLTK_BUILD_FLTK_OPTIONS=OFF -DFLTK_USE_SYSTEM_LIBJPEG=OFF -DFLTK_USE_SYSTEM_LIBPNG=OFF -DFLTK_USE_SYSTEM_ZLIB=OFF -DFLTK_USE_SYSTEM_LIBDECOR=OFF -DFLTK_USE_LIBDECOR_GTK=OFF -DFLTK_OPTION_STD=ON -DFLTK_OPTION_PRINT_SUPPORT=OFF -DFLTK_BUILD_SHARED_LIBS=OFF -DFLTK_BUILD_FORMS=OFF

cmake --build ../build
